version: '3'
services:
  app:
    build: ./docker/app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
  db:
    build: ./docker/db
    ports:
      - "5432:5432"