version: '3'
services:
  app:
    build: ./docker/app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    restart: on-failure

  db:
    build: ./docker/db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d main -U docker" ]
      interval: 5s
      timeout: 5s
    ports:
      - "5432:5432"